---
title: "trythis12"
author: "Jeongmin"
date: "2019년 3월 8일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(psych)
library(ggplot2)
library(gridExtra)
library(tibble)
library(stringi)
library(ggiraph)
library(devtools)

load('./data/data.rda')

```

## 1) "죽cls과 매cls의 수학성적은 차이가 없다" 라는 가설을 검증하시오.

```{r}


# 1. 데이터 준비
jmmath = data %>% filter(cls %in% c('죽', '매')) %>% select(cls, math)
jmmath$cls = factor(jmmath$cls, levels=c('죽','매'), labels=c('죽', '매'))

# 2. 데이터 확인 (기술통계 + 그래프)
describeBy(jmmath$math, jmmath$cls, mat = T)
orgpar = par(no.readonly = T)
boxplot(jmmath$math ~ jmmath$cls)
layout(matrix(c(1,1,2,3), 2, 2, byrow = T))
boxplot(jmmath$math ~ jmmath$cls)
hist(jmmath$math[jmmath$cls == '죽'])
hist(jmmath$math[jmmath$cls == '매'])
par(orgpar)

# 3. 등분산 검정
var.test(jmmath$math ~ jmmath$cls, data = jmmath)

# 4. t-test 수행
t.test(jmmath$math ~ jmmath$cls, data = jmmath,
       alternative = c("two.sided"),
       var.equal = T,                 # 등분산검증의 p-value < 0.05 이면 False로!
       conf.level = 0.95)

# 5. 결과 그래프 
mu = 63.5; se = 2.144661; rn = sort(rnorm(1000, mu, se))
plot(rn, dnorm(rn, mu, se), col='green', type = 'l', main = '평균점수',
     xlim = c(50, 80), ylim = c(0, 0.25)) 
abline(v=mu, col="green", lty=5)
par(new = T)  
mu = 63.8; se = 2.114145; rn = sort(rnorm(1000, mu, se))
plot(rn, dnorm(rn, mu, se), col='red', type = 'l', main = '평균점수',
     xlim = c(50, 80), ylim = c(0, 0.25))
abline(v=mu, col="red", lty=5)

```

## Including Plots

You can also embed plots, for example:

```{r}
# 2. 
describeBy(data$math, data$cls, mat = T)

# 3. 그래프로 확인하기
ggplot(data, aes(x=cls, y=math)) +
  geom_boxplot(outlier.color = 'blue') +
  ggtitle("각cls 수학 성적")

ggplot(data, aes(x=math)) +
  geom_histogram(binwidth = 10, col='white') +
  facet_grid(. ~ data$cls)   # 그룹별로 그려라!

# 4-1. 등분산(분산의 동질성) 검정 (p-value > 0.05 면 등분산)
bartlett.test(data$math ~ data$cls, data=data)  # ⇒ p-value = 0.8497 ⇒ 약 85% 동질하다

aaa = aov(data$math ~ data$cls, data=data)
summary(aaa)   

TukeyHSD(aaa)

plot(TukeyHSD(aaa)) 



draw = function(rn, mu, se, col) {
  plot(rn, dnorm(rn, mu, se), col=col, type = 'l',
       xlim = c(50, 80), ylim = c(0, 0.25))
  abline(v=mu, col=col, lty=5)
}


mu = 63.59167; se = 2.020535; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'red')
par(new = T)
mu = 63.08333; se = 2.028632; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'blue')
par(new = T)
mu = 63.84167; se = 2.114145; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'green')
par(new = T)
mu = 63.46667; se = 2.144661; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'black')





legend('topright',
       legend=c('국', '난', '매', '죽'),
       pch=8,
       col=c('red', 'blue', 'green', 'black'),
       bg='gray')



```
